# Scorecards
I am going to determine how to calculate scorecards for each county.

Current Plan:
1. Make methods for all rubric itmes
2. Figure out weight for all items
3. Design scorecard

# Making Methods

I think I might want to make a function using pandas that creates a table for a county with all the results. I need to decide which rows to keep, remove, add, etc.. Let's look at the data.

In [2]:
import pandas as pd
import csv # don't think I need

df = pd.read_csv('engLocAccuracy1.csv')

df.head()

,date,location,query,computer,domain,title,org-position,link,bolded,type,state,gov_type,gov_state,accuracy
0,10/25/24,Yuma County,independent candidates,Computer1,ballotpedia.org,"Presidential candidates, 2024",1,https://ballotpedia.org/Presidential_candidate...,['candidates'],organic,AZ,NaN,NaN,NaN
1,10/25/24,Yuma County,independent candidates,Computer1,nytimes.com,Who Are the 2024 Presidential Election Candida...,2,https://www.nytimes.com/interactive/2023/us/po...,['Independent'],organic,AZ,NaN,NaN,NaN
2,10/25/24,Yuma County,independent candidates,Computer1,usnews.com,Thinking of Voting for a Third-Party Candidate...,3,https://www.usnews.com/news/elections/articles...,['independent'],organic,AZ,NaN,NaN,NaN
3,10/25/24,Yuma County,independent candidates,Computer1,wikipedia.org,Third-party and independent candidates for the...,4,https://en.wikipedia.org/wiki/Third-party_and_...,['independent candidates'],organic,AZ,NaN,NaN,NaN
4,10/25/24,Yuma County,independent candidates,Computer1,nytimes.com,Maps: Where Independent and Third-Party Presid...,5,https://www.nytimes.com/interactive/2024/us/po...,['independent candidates'],organic,AZ,NaN,NaN,NaN

We will keep: location, query, domain, title, link, state, gov_type, gov_state, and accuracy  
Afterwards, we will aggregate the tables to become one for each county.

In [4]:
df.drop(['date', 'computer', 'bolded', 'type'], axis=1, inplace=True)
df.head()

,location,query,domain,title,org-position,link,state,gov_type,gov_state,accuracy
0,Yuma County,independent candidates,ballotpedia.org,"Presidential candidates, 2024",1,https://ballotpedia.org/Presidential_candidate...,AZ,NaN,NaN,NaN
1,Yuma County,independent candidates,nytimes.com,Who Are the 2024 Presidential Election Candida...,2,https://www.nytimes.com/interactive/2023/us/po...,AZ,NaN,NaN,NaN
2,Yuma County,independent candidates,usnews.com,Thinking of Voting for a Third-Party Candidate...,3,https://www.usnews.com/news/elections/articles...,AZ,NaN,NaN,NaN
3,Yuma County,independent candidates,wikipedia.org,Third-party and independent candidates for the...,4,https://en.wikipedia.org/wiki/Third-party_and_...,AZ,NaN,NaN,NaN
4,Yuma County,independent candidates,nytimes.com,Maps: Where Independent and Third-Party Presid...,5,https://www.nytimes.com/interactive/2024/us/po...,AZ,NaN,NaN,NaN